#!/usr/bin/env racket
;;
;; SPDX-License-Identifier: ISC
;;
;; Copyright © 2019 rsiddharth <s@ricketyspace.net>
;;

#lang racket/base

(require racket/port)

(require net/http-client)
(require openssl)

(require sxml/sxpath)


(define HOST "news.ycombinator.com")

(define (fp)
  "Fetch HN Front Page."
  (let ((hc (http-conn-open HOST
                            #:ssl? (ssl-make-client-context 'secure)
                            #:port 443)))
    (define-values (status headers port)
      (http-conn-sendrecv! hc "/"))
    (port->string port)))
